#:schema https://api.nuon.co/v1/general/config-schema?type=install

name = "retool_dev"
approval_option = "approve-all"

[aws_account]
  region = "us-east-1"

[inputs]
  license_key = "abc123"
  number_type = "10"
  json_type = '{"key": "value"}'
  bool_type = "true"
