#:schema https://api.nuon.co/v1/general/config-schema?type=install

name = "retool_dev"
approval_option = "approve-all"

[aws_account]
  region = "us-east-1"

[[inputs]]
  license_key = "this will not sync" # sensitive inputs are skipped
  number_type = "12"
  json_type = '{"key": "value"}'
  bool_type = "true"
  required_type = "custom_value"
