# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
---
version: 2
updates:
  - package-ecosystem: "gomod"  # See documentation for possible values
    directory: "/"  # Location of package manifests
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/New_York"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:20"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "services/api/infra"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "services/orgs-api/infra"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "services/workers-apps/infra"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "services/workers-deployments/infra"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "services/workers-executors/infra"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "services/workers-installs/infra"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "services/workers-instances/infra"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "services/workers-orgs/infra"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"
