# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
---
version: 2
updates:
  - package-ecosystem: "gomod"  # See documentation for possible values
    directory: "/"  # Location of package manifests
    schedule:
      day: "sunday"
      interval: "weekly"
      time: "07:05"
      timezone: "America/New_York"
    open-pull-requests-limit: 1

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      day: "sunday"
      interval: "weekly"
      time: "07:00"
      timezone: "America/New_York"

  # terraform workspaces
  - package-ecosystem: "terraform"
    directory: "services/ctl-api/infra"
    schedule:
      day: "sunday"
      interval: "weekly"
      time: "07:10"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "services/workers-apps/infra"
    schedule:
      day: "sunday"
      interval: "weekly"
      time: "07:20"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "services/workers-deployments/infra"
    schedule:
      day: "sunday"
      interval: "weekly"
      time: "07:25"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "services/workers-executors/infra"
    schedule:
      day: "sunday"
      interval: "weekly"
      time: "07:30"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "services/workers-installs/infra"
    schedule:
      day: "sunday"
      interval: "weekly"
      time: "07:35"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "services/workers-instances/infra"
    schedule:
      day: "sunday"
      interval: "weekly"
      time: "07:40"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "services/workers-orgs/infra"
    schedule:
      day: "sunday"
      interval: "weekly"
      time: "07:45"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "infra/orgs"
    schedule:
      day: "sunday"
      interval: "weekly"
      time: "07:45"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "infra/datadog"
    schedule:
      day: "sunday"
      interval: "weekly"
      time: "07:45"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "infra/dns"
    schedule:
      day: "sunday"
      interval: "weekly"
      time: "07:45"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "infra/eks"
    schedule:
      day: "sunday"
      interval: "weekly"
      time: "07:45"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "infra/github"
    schedule:
      day: "sunday"
      interval: "weekly"
      time: "07:45"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "infra/powertools"
    schedule:
      day: "sunday"
      interval: "weekly"
      time: "07:45"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "infra/temporal"
    schedule:
      day: "sunday"
      interval: "weekly"
      time: "07:45"
      timezone: "America/New_York"

  - package-ecosystem: "terraform"
    directory: "infra/terraform"
    schedule:
      day: "sunday"
      interval: "weekly"
      time: "07:45"
      timezone: "America/New_York"

registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.NUON_NPM_GITHUB_TOKEN}}
