name = "Post Deprovision Sandbox"
timeout = "30s"

[[triggers]]
type = "post-deprovision-sandbox"

# echo something out
[[steps]]
name = "echo"
command = "echo 'post deprovision sandbox'"

[steps.env_vars]
TEST_NUON_VAR = "{{.nuon.install.id}}"

[[steps]]
name = "env"
command = "env"
