name = "Pre Reprovision Sandbox"
timeout = "30s"

[[triggers]]
type = "pre-reprovision-sandbox"

# echo something out
[[steps]]
name = "echo"
command = "echo 'pre reprovision sandbox'"

[steps.env_vars]
TEST_NUON_VAR = "{{.nuon.install.id}}"

[[steps]]
name = "env"
command = "env"

