name = "Pre Deploy All Components"
timeout = "30s"

[[triggers]]
type = "pre-deploy-all-components"

# echo something out
[[steps]]
name = "echo"
command = "echo 'pre deploy-all'"

[steps.env_vars]
TEST_NUON_VAR = "{{.nuon.install.id}}"

[[steps]]
name = "env"
command = "env"
