---
port: 4321
type: service
local_only: true
env:
env_secrets:
disable_watch: true
local_startup_cmds: []
local_cmds:
  - npm run dev
namespace: wiki
sources:
  - src: wiki/
    dst: wiki/
docker_cmds:
  - ports:
     - 4321
