#:schema http://localhost:8081/v1/general/config-schema?source=runner
runner_type     = "aws"
helm_driver     = "configmap"
init_script_url = "https://raw.githubusercontent.com/nuonco/runner/refs/heads/main/scripts/aws/init-mng.sh"

[env_vars]
runner-env-var = "runner-env-var"
