terraform_version = "1.11.3"

[public_repo]
directory = "."
repo      = "nuonco/aws-eks-sandbox"
branch    = "main"

[env_vars]
cluster_name         = "n-{{.nuon.install.id}}"

[vars]
cluster_name         = "n-{{.nuon.install.id}}"
account_id           = "{{.nuon.install_stack.outputs.account_id}}"
enable_nuon_dns      = "true"
public_root_domain   = "{{ .nuon.inputs.inputs.root_domain }}"
internal_root_domain = "internal.{{ .nuon.inputs.inputs.root_domain }}"

[[var_file]]
contents = "./sandbox.tfvars"
