#:schema http://localhost:8081/v1/general/config-schema?type=runner
runner_type     = "aws"
init_script_url = "https://raw.githubusercontent.com/nuonco/runner/refs/heads/main/scripts/aws/init-mng.sh"
