name = "Pre Component"
timeout = "30s"

[[triggers]]
type = "pre-deploy-component"
component_name = "container_image"

# echo something out
[[steps]]
name = "echo"
command = "echo 'hello world'"

[steps.env_vars]
TEST_NUON_VAR = "{{.nuon.install.id}}"

