#:schema https://api.nuon.co/v1/general/config-schema?type=action

name    = "run_shell_command"
timeout = "1m"

[[triggers]]
type = "manual"

[[steps]]
name    = "execute command using bash"
inline_contents = """
#!/usr/bin/env bash

set -eo pipefail

echo >&2 "executing command..."
$CMD
"""
[steps.env_vars]
CMD = "ls"
