---
apiVersion: v2
name: api-gateway
description: A Helm chart for deploying our api
type: application
version: 0.1.0
appVersion: "0.0.1"

dependencies:
  - name: common
    version: 0.8.1
    repository: s3://nuon-charts/charts
