---
port: 3000
type: api
env:
  NUON_API_URL: "http://localhost:8081"
  NEXT_PUBLIC_WEBAPP_URL: "local.installer.nuon.dev"
watch_ignore_dirs:
  - .next/
local_startup_cmds: []
local_cmds:
  - npm run dev
