---
env:
  DB_HOST: postgres
  DB_NAME: api
  DB_PASSWORD: password
  DB_SSL_MODE: disable
  DB_USE_IAM: false
  DB_USE_SSL: false
  GIT_REF: local
  DISABLE_METRICS: true
  HTTP_PORT: 8080
env_secrets:
  GITHUB_APP_KEY:
    name: graphql-api-github-app-key
    key: github_app_key
local_env:
  DB_HOST: localhost
local_cmds:
  - 'go run . worker --domain=builds'
  - 'go run . worker --domain=apps'
  - 'go run . worker --domain=installs'
  - 'go run . worker --domain=orgs'
  - 'go run . worker --domain=deploys'
  - 'go run . server'
run_cmd: server
port: 8080
type: api
