---
env:
  DB_HOST: localhost
  DB_NAME: api
  DB_PASSWORD: password
  DB_SSL_MODE: disable
  DB_USE_IAM: false
  DB_USE_SSL: false
  GIT_REF: local
  GITHUB_APP_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEA1gw2Krloet9/X8k93XXJF6u628RDOKj8gw7Yu47QjK1ttkzM
    4x71b5tvwXzCZ5kW6T4AAOkjW4pykxZH+P+3j21RGdhIUTPbOQFgkguJcQANd8Gp
    gFAWKtTAK30vLFQHzOra82wYQDuueSov2ABR9GTv3QUxT0tGUWjFxvWDcUT8FtUO
    doAEAOdfuh3AA9pbN1MtSP3wsNHdvjzsoSAM/EbCozCqGccpal6OJl+eiyCRPA3I
    3366x2rD0LR/IgN99xuLbI/1m1qSF6CTSCrXjBKzBzXrLipyDYDAKcrooJ28cq/j
    q2/XLTOB2vK5Ut1ofTXvK9uFhSiB9EYJnfKeGQIDAQABAoIBAQCmy1tGTbZx0UlT
    XeD8erVZ4bM5X6W2OFCU2/Pdq7stdFOC9DPQZCaDcs9SKiLfUbc9x9d+3i10Pt1r
    arho+vOSK3BAQH6R8GPK9xzGkYDnclAMWvf3ifDMLX8WJHWnCFAPyY8WkswO+bLK
    riocGpvCYwla5Jn5HUJNW+SKVnS3xMn/8YtcassC0pkJ2gsjx+8HQ4ik8H/4Hz9y
    CBzO8CGdL/TpWBoDyazOISvG87VqJBPXtKlm92fbm/qmjhc7+9dl4zJirNOZs2h2
    4q7OlokojZ4rhH42Aen0utVWMCtxYtHJ2qMEbFQo6C1dGEJMeVRC7sFpdPP7XKXc
    2SNHC3JlAoGBAO4ShFhIGUmmNCXOTiQEiuO3NdUkvq+XoukR2xffi2TNGZZ+s4z6
    H044AGxwDIc5A16qE/SYJ67uUcuYOtkudzi5cLrbKd+vzD2r5YwcJQjxKiPSPJd7
    RXsExc1iQoezXumlLGtPAG4LhI9Y6lMsYWjEJls3xYhqujfkxJ0oOk9fAoGBAOYq
    ji6x3eu3r1ofC/GbcxV5QRdafDIXhKCKrZnKQNCPnYeHpHFN+cr8et2cwwFvfePY
    ScxcOrwWwZCOxbQyizIg2wWN3mHNOSvKV4espSLPY4palPOUk4G5yhJcMMgF0mzb
    zEg3tFlhTfKge4vyyLED5GkobEhDk/RdI6IQ6x2HAoGBAJ1+PHUWhTwWqmrUNxdW
    tfb87azqWQdafhhHirQZW2K82A+aE/fQQ8OAAq+51F/kVJlcVEU8Hwx3dj8EnvGr
    7ozlCHFkqSfkaW3m+L0epVVsDR+TZigkEYvXVW+QcEjLXZ+deGwo4DTsg648+Q86
    zdn74Q/5LkEXscdmHLeGtERrAoGAUUkMJ6+HSVz4n6JBTJVyok3NUBsTq3kkzLHN
    N3f3RfDCWH/t8lnwcuCR37wiHlqqohHblkGoOI7s00moxsfm4tA5qY99zxp0K2Pt
    X6v4Mf/+DnmJCzEYmwLrO2q1i56Kvwks7wBFQB+eMKa+myEmAWX3f6/X9flvwig2
    kmDZN/cCgYEAhg6KQZsOzqdUZJ5LT3f8gMIBFjLsgur457sbH6pY5VeTw87sww9H
    NRi5zngX9fh10PhOPfCr39goZF5bhpYLJkmENKD/dSq0+YmvKSt6gNrA7Uv94hm3
    +pEvTPY701+InxCVa0aK6qZVSwLYOeqGDpzi8pu8/CtcWsGDtQeP480=
    -----END RSA PRIVATE KEY-----
  DISABLE_METRICS: true
  TEMPORAL_NAMESPACE: default
  TEMPORAL_HOST: localhost:7233
port: 8080
type: api
