apiVersion: v1
kind: Service
metadata:
  labels:
    app: remote-buildkit-agent
    {{- include "buildkit.labels" . | nindent 4 }}
  name: buildkitd
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.buildkit.port }}
      protocol: TCP
  selector:
    app: remote-buildkit-agent
