name = "Post Component Deploy"
timeout = "30s"

[[triggers]]
type = "pre-deploy-component"
component_name = "container_image"

# echo something out
[[steps]]
name = "echo"
command = "echo 'pre component deploy'"

[steps.env_vars]
TEST_NUON_VAR = "{{.nuon.install.id}}"

[[steps]]
name = "env"
command = "env"
