---
replicaCount: 2
command: ["/bin/service", "server"]

workers:
  - name: workers-apps
    minReplicas: 1
    maxReplicas: 1
    command: ["/bin/service", "worker", "apps"]
  - name: workers-builds
    minReplicas: 1
    maxReplicas: 1
    command: ["/bin/service", "worker", "builds"]
  - name: workers-installs
    minReplicas: 1
    maxReplicas: 1
    command: ["/bin/service", "worker", "installs"]
  - name: workers-deploys
    minReplicas: 1
    maxReplicas: 1
    command: ["/bin/service", "worker", "deploys"]
  - name: workers-orgs
    minReplicas: 1
    maxReplicas: 1
    command: ["/bin/service", "worker", "orgs"]

configmap:
  enabled: true
  values:
    TEMPORAL_HOST: temporal-frontend-headless.temporal.svc.cluster.local:7233
    DB_USE_SSL: "true"
    DB_SSL_MODE: verify-full
    DB_USE_ZAP: "true"
    DB_USE_IAM: "true"
    DB_MIGRATIONS_PATH: /migrations

envSecrets:
  - name: "GITHUB_APP_KEY"
    valueFrom:
      name: graphql-api-github-app-key
      key: github_app_key

controller:
  enabled: true
  type: deployment
  annotations: {}
  labels: {}
  replicas: 1
  revisionHistoryLimit: 3

# image configuration
image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

serviceAccount:
  # Specifies whether a service account should be created
  enabled: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true,
  # a name is generated using the fullname template
  name:

service:
  main:
    type: ClusterIP
    primary: true
    enabled: true
    annotations: {}
    ports:
      http:
        enabled: true
        primary: true
        port: 80
        targetPort: 8080
        protocol: TCP

probes:
  # Liveness probe configuration
  # @default  See below
  liveness:
    # Enable the liveness probe
    enabled: false
    # Set this to `true` if you wish to specify your own livenessProbe
    custom: false
    # The spec field contains the values for the default livenessProbe.
    # If `custom: true`, this field holds the definition of the probe.
    # @default  See below
    spec:
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3

  #  Readiness probe configuration
  # @default  See below
  readiness:
    #  Enable the readiness probe
    enabled: true
    #  Set this to `true` if you wish to specify your own readinessProbe
    custom: false
    # The spec field contains the values for the default readinessProbe.
    # If `custom: true`, this field holds the definition of the readinessProbe.
    # @default  See below
    spec:
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
