#:schema https://api.nuon.co/v1/general/config-schema?type=runner
runner_type = "aws"
helm_driver = "configmap"
init_script_url = "https://raw.githubusercontent.com/nuonco/runner/refs/heads/main/scripts/aws/init-mng.sh"

[env_vars]
foo = "bar"
