type        = "aws-cloudformation"
name        = "nuon-demos-eks-simple-{{.nuon.install.id}}"
description = "QuickLink to install runner for BYOC Nuon: Install {{.nuon.install.id}}"

# nested stack
vpc_nested_template_url    = "{{.nuon.install.id}}"
runner_nested_template_url = "{{.nuon.install.id}}"
