#:schema https://api.nuon.co/v1/general/config-schema?type=install

name = "simple_install"
approval_option = "approve-all"

[aws_account]
  region = "us-east-1"

[inputs]
  root_domain = "byoc.simple.example.com"
