name         = "db_password"
display_name = "Database Password"
description  = "Base64 encoded database password"
required     = true

kubernetes_sync             = true
kubernetes_secret_namespace = "default"
kubernetes_secret_name      = "db-password"
format = "base64"

