#:schema https://api.nuon.co/v1/general/config-schema?type=terraform
name              = "s3_bucket"
type              = "terraform_module"
terraform_version = "1.11.3"

[public_repo]
repo      = "mrwong/s3_for_tests"
directory = "."
branch    = "main"

[vars]
bucket_name_prefix = "{{.nuon.install.id}}"
region      = "{{ .nuon.install_stack.outputs.region }}"

