terraform_version = "1.11.3"

[connected_repo]
repo      = "powertoolsdev/mono"
directory = "infra/datadog"
branch    = "main"

[env_vars]
CLUSTER_NAME = "{{.nuon.install.id}}"

[vars]
account_id = "{{.nuon.install_stack.outputs.account_id}}"
