terraform_version = "1.11.3"

[public_repo]
repo      = "sharkymark/aws-min-sandbox"
directory = "/"
branch    = "main"

[env_vars]
CLUSTER_NAME = "{{.nuon.install.id}}"

[vars]
account_id = "{{.nuon.install_stack.outputs.account_id}}"
