type = "aws-cloudformation"
name = "nuon-install-{{.nuon.install.id}}"
description = "Quick link to install runner for {{.nuon.install.id}}"
# nested stack
vpc_nested_template_url    = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/sandbox/exp/aws-cloudformation-templates/v0.1.4/vpc/eks/default/stack.yaml"
runner_nested_template_url = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/sandbox/exp/aws-cloudformation-templates/v0.1.6/runner/asg/stack.yaml"
