---
name: artifact
"on":
  workflow_call:
    inputs:
      artifact:
        type: string
        required: true
      publish:
        type: boolean
        required: true
      tag:
        type: string
        required: true
    outputs: {}

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: ğŸŒ lint
    uses: ./.github/workflows/artifact_lint.yml
    secrets: inherit
    with:
      artifact: ${{ inputs.artifact }}

  test:
    name: ğŸŒ test
    uses: ./.github/workflows/artifact_test.yml
    secrets: inherit
    with:
      artifact: ${{ inputs.artifact }}

  publish:
    name: ğŸŒ publish
    uses: ./.github/workflows/artifact_publish.yml
    #if: ${{ inputs.publish }}
    secrets: inherit
    #needs:
    #- test
    #- lint
    with:
      artifact: ${{ inputs.artifact }}
      tag: ${{ inputs.tag }}
