---
name: artifact
"on":
  workflow_call:
    inputs:
      dir:
        type: string
        required: true
      tag:
        type: string
        required: true
      is_promotion:
        type: boolean
        required: true
    outputs: {}

defaults:
  run:
    shell: bash

jobs:
  outputs:
    name: ğŸŒ outputs
    uses: ./.github/workflows/artifact_outputs.yml
    secrets: inherit
    with:
      dir: ${{ inputs.dir }}

  lint:
    name: ğŸŒ lint
    uses: ./.github/workflows/artifact_lint.yml
    secrets: inherit
    with:
      dir: ${{ inputs.dir }}

  test:
    name: ğŸŒ test
    uses: ./.github/workflows/artifact_test.yml
    secrets: inherit
    with:
      dir: ${{ inputs.dir }}

  publish:
    name: ğŸŒ publish
    uses: ./.github/workflows/artifact_publish.yml

    # we run publish under two circumstances:
    # when a promotion is happening and the artifact uses promotions
    # when a PR is merged and the artifact does _not_ use promotions
    if: |
      (inputs.is_promotion && needs.outputs.outputs.use_promotions == 'true') ||
      (
          !inputs.is_promotion &&
          needs.outputs.outputs.use_promotions != 'true' &&
          github.event_name != 'pull_request'
      )
    secrets: inherit
    needs:
      - outputs
      - test
      - lint
    with:
      dir: ${{ inputs.dir }}
      tag: ${{ inputs.tag }}
