---
name: artifact
"on":
  workflow_call:
    inputs:
      artifact:
        type: string
        required: true
      publish:
        type: boolean
        required: true
      tag:
        type: string
        required: true
    outputs: {}

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: ğŸŒ lint
    uses: ./.github/workflows/artifact_lint.yml
    secrets: inherit
    with:
      artifact: ${{ startsWith(inputs.artifact, 'helm-') && 'demo' || inputs.artifact }}
      base_dir: ${{ startsWith(inputs.artifact, 'helm') && 'charts' || 'bins'}}

  test:
    name: ğŸŒ test
    uses: ./.github/workflows/artifact_test.yml
    secrets: inherit
    with:
      artifact: ${{ startsWith(inputs.artifact, 'helm-') && 'demo' || inputs.artifact }}
      base_dir: ${{ startsWith(inputs.artifact, 'helm') && 'charts' || 'bins'}}

  publish:
    name: ğŸŒ publish
    uses: ./.github/workflows/artifact_publish.yml
    if: ${{ inputs.publish }}
    secrets: inherit
    needs:
      - test
      - lint
    with:
      artifact: ${{ startsWith(inputs.artifact, 'helm-') && 'demo' || inputs.artifact }}
      base_dir: ${{ startsWith(inputs.artifact, 'helm') && 'charts' || 'bins'}}
      tag: ${{ inputs.tag }}
