---
name: artifacts
"on":
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: read
  packages: write
  pull-requests: write
  statuses: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  # NOTE(jm): we only want to "cancel" in flight jobs if pushing to an existing PR. If this is running on main, do not
  # cancel previous jobs.
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:
  changes:
    name: ðŸ” changes
    runs-on: ubuntu-latest
    outputs:
      artifacts: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: read ci triggers file
        uses: pietrobolcato/action-read-yaml@1.1.0
        id: ci_triggers
        with:
          config: ci-triggers.yml

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: ${{ steps.ci_triggers.outputs['artifacts'] }}

  tag:
    name: Determine short ref
    runs-on: ubuntu-latest
    outputs:
      git_ref: ${{steps.git_ref.outputs.git_ref}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set git_ref output
        id: git_ref
        run: echo "git_ref=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  artifacts:
    # since this runs as a matrix, name shows as `ðŸš¢ (workers-orgs)`
    name: ðŸš¢
    needs:
      - changes
      - tag
    if: ${{ needs.changes.outputs.artifacts != '[]' && needs.changes.outputs.artifacts != '' }}
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.changes.outputs.artifacts) }}
    uses: ./.github/workflows/artifact.yml
    with:
      dir: ${{matrix.dir}}
      tag: ${{ needs.tag.outputs.git_ref }}
      is_promotion: false
    secrets: inherit

  update_status:
    name: update status
    if: github.event_name == 'pull_request' && always()
    needs:
      - artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: martialonline/workflow-status@v4.1
        id: check
      - name: Update status
        uses: ouzi-dev/commit-status-updater@v2.0.1
        with:
          name: artifacts âœ…
          status: ${{steps.check.outputs.status}}
