---
name: CI
"on":
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: read
  packages: write
  pull-requests: write
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  REPO_NAME: ${{ github.event.repository.name }}
  DEPENDENCY_REPOS: go-aws-assume-role,go-common,go-generics,go-helm,go-terraform,go-kube,go-sender,go-uploader,go-waypoint,protos

jobs:
  terraform:
    name: Get Terraform outputs
    runs-on: ubuntu-latest
    env:
      TF_OUT: ${{ github.workspace }}/tf-out.json
    timeout-minutes: 7
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_KEY }}

      - name: Init terraform
        shell: bash
        working-directory: infra
        env:
          TF_WORKSPACE: stage
        run: |
          terraform init

      - name: Get terraform outputs
        working-directory: infra
        env:
          TF_WORKSPACE: stage
        run: |
          terraform-bin output -json > ${{ env.TF_OUT }}

      - name: Parse terraform outputs
        uses: powertoolsdev/action-tf-output@main
        with:
          file: ${{ env.TF_OUT }}

      - name: Save terraform outputs
        run: |
          printenv | grep "TFO_" > .tfenv

      - name: Save outputs
        uses: actions/upload-artifact@v3
        with:
          name: env-${{ github.run_id }}
          path: .tfenv
          if-no-files-found: error
          retention-days: 1

  lint:
    name: Lint
    needs: terraform
    runs-on: ubuntu-latest
    timeout-minutes: 9
    steps:
      - name: Generate token
        id: generate_token
        uses: powertoolsdev/action-app-token@main
        with:
          app_id: ${{ secrets.CROSS_REPO_APP_ID }}
          installation_id: ${{ secrets.CROSS_REPO_INSTALLATION_ID }}
          private_key: ${{ secrets.CROSS_REPO_PRIV_KEY }}
          repositories: ${{ env.DEPENDENCY_REPOS }}

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Download terraform outputs
        uses: actions/download-artifact@v3
        with:
          name: env-${{ github.run_id }}

      - name: Setup environment
        run: |
          cat .tfenv >> "$GITHUB_ENV"

      - name: Setup for CI
        uses: powertoolsdev/action-setup-ci@main
        with:
          tfcloud_token: ${{ secrets.TF_API_KEY }}
          clone_token: ${{ steps.generate_token.outputs.token }}
          aws_role: ${{ env.TFO_GH_ROLE_ARN }}
          aws_region: ${{ env.TFO_REGION }}

      - name: Terraform init
        env:
          TF_WORKSPACE: stage
        run: |
          terraform -chdir=infra init -backend=false

      - name: Lint
        run: |
          earthly \
            ${{ env.EARTHLY_EXTRA_ARGS }} \
            --remote-cache=ghcr.io/${{ github.repository }}:lint \
            +lint

      - name: Run helm lint
        shell: bash
        working-directory: k8s
        run: |
          helm lint .

  test:
    name: Test
    needs: terraform
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - name: Generate token
        id: generate_token
        uses: powertoolsdev/action-app-token@main
        with:
          app_id: ${{ secrets.CROSS_REPO_APP_ID }}
          installation_id: ${{ secrets.CROSS_REPO_INSTALLATION_ID }}
          private_key: ${{ secrets.CROSS_REPO_PRIV_KEY }}
          repositories: ${{ env.DEPENDENCY_REPOS }}

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Download terraform outputs
        uses: actions/download-artifact@v3
        with:
          name: env-${{ github.run_id }}

      - name: Setup for CI
        uses: powertoolsdev/action-setup-ci@main
        with:
          tfcloud_token: ${{ secrets.TF_API_KEY }}
          clone_token: ${{ steps.generate_token.outputs.token }}

      - name: Setup terraform environment
        run: |
          cat .tfenv >> "$GITHUB_ENV"

      - name: Run earthly
        if: always()
        run: |
          earthly \
            --allow-privileged \
            ${{ env.EARTHLY_EXTRA_ARGS }} \
            --remote-cache=ghcr.io/${{ github.repository }}:test-integration \
            +test-integration

  update_status:
    name: Update status
    needs:
      - lint
      - test
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    timeout-minutes: 7
    steps:
      - name: Update status
        uses: ouzi-dev/commit-status-updater@v2.0.1
        with:
          name: Required CI Checks
          status: success

  release:
    name: Release
    needs:
      - terraform
    if: github.event_name != 'pull_request'
    uses: powertoolsdev/.github/.github/workflows/release.yml@main
    secrets: inherit

  deploy-stage:
    name: Deploy (stage)
    needs:
      - release
    if: github.event_name != 'pull_request'
    uses: powertoolsdev/.github/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      env: stage
      tag: ${{ needs.release.outputs.image_tag }}

  deploy-prod:
    name: Deploy (prod)
    needs:
      - release
      - deploy-stage
    if: github.event_name != 'pull_request'
    uses: powertoolsdev/.github/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      env: prod
      tag: ${{ needs.release.outputs.image_tag }}
