---
name: CI
"on":
  pull_request:

  push:
    branches:
      - main

permissions:
  contents: write
  issues: read
  packages: write
  pull-requests: read
  statuses: write

jobs:
  go-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run lints
        uses: powertoolsdev/action-reviewdog@main
        with:
          terraform: 'false'

      - name: Setup earthly
        if: always()
        uses: earthly/actions-setup@v1.0.1
        with:
          version: "latest"

      - name: Setup env
        if: always() && github.event_name != 'pull_request'
        run: echo "EARTHLY_EXTRA_ARGS=--push" >> "$GITHUB_ENV"

      - id: earthly-ci
        if: always()
        name: Run earthly
        run: |
          earthly \
            --ci \
            ${{ env.EARTHLY_EXTRA_ARGS }} \
            --remote-cache=ghcr.io/powertoolsdev/go-common:gha \
            +ci

      - name: Update status
        if: always() && github.event_name == 'pull_request'
        uses: ouzi-dev/commit-status-updater@v1.1.2
        with:
          name: Required PR Checks
          status: "${{ steps.earthly-ci.outcome }}"

      - name: Bump version and push tag
        if: github.event_name != 'pull_request'
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
