---
name: promote nuonctl
on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: read
  packages: write
  pull-requests: write
  statuses: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  # we use the merged pr to see if the PR was labeled "promote", but since this _only_ runs after the PR is merged
  # (on main), we have to use an action to pull it from the github api.
  merged_pr:
    name: Get merged PR
    runs-on: ubuntu-latest
    outputs:
      promote: ${{steps.output.outputs.promote}}
    steps:
      - uses: actions-ecosystem/action-get-merged-pull-request@v1
        name: get merged pr
        id: merged_pr
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: update promote output
        id: output
        if: steps.merged_pr.outputs.labels == 'promote-nuonctl'
        run: echo "promote=true" >> "$GITHUB_OUTPUT"

  tag:
    name: Determine short ref
    needs:
      - merged_pr
    runs-on: ubuntu-latest
    if: ${{ needs.merged_pr.outputs.promote == 'true' }}
    outputs:
      git_ref: ${{steps.git_ref.outputs.git_ref}}
      semver: ${{ steps.semver.outputs.nextStrict }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set git_ref output
        id: git_ref
        run: echo "git_ref=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Determine next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          minorList: ""
          patchAll: true

  start_slack_notifications:
    name: update promotions channel
    needs:
      - tag
      - merged_pr
    if: ${{ needs.merged_pr.outputs.promote == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_ICON_EMOJI: ü§ñ
          SLACK_USERNAME: github-bot
          SLACK_WEBHOOK: ${{ secrets.PROMOTIONS_SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: |
            ‚õ¥  promoting nuonctl `${{ needs.tag.outputs.git_ref }}`
            *stage* - true
            *prod* - true

  services:
    # since this runs as a matrix, name shows as `üö¢ (workers-orgs)`
    name: üö¢
    needs:
      - tag
      - merged_pr
    if: ${{ needs.merged_pr.outputs.promote == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        service:
          - nuonctl
    uses: ./.github/workflows/service.yml
    with:
      service: ${{matrix.service}}
      tag: ${{ needs.tag.outputs.semver }}
      prod: true
      stage: false
    secrets: inherit

  bump_tag:
    name: bump tag
    needs:
      - tag
      - merged_pr
    if: ${{ needs.merged_pr.outputs.promote == 'true' }} && always()
    runs-on: ubuntu-latest
    steps:
      - name: Push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ needs.tag.outputs.semver }}

  update_statuses:
    name: update statuses
    if: needs.merged_pr.outputs.promote == 'true' && always()
    needs:
      - tag
      - services
      - merged_pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: martialonline/workflow-status@v4.1
        id: check
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_ICON_EMOJI: ü§ñ
          SLACK_USERNAME: github-bot
          SLACK_WEBHOOK: ${{ secrets.PROMOTIONS_SLACK_WEBHOOK_URL }}
          SLACK_COLOR: ${{steps.check.outputs.status}}
          SLACK_MESSAGE: |
            ${{ steps.check.outputs.status == 'success' && 'üèÅüèÅ' || 'üö®üö®' }} finished promoting nuonctl `${{ needs.tag.outputs.git_ref }}`
            *prod* - true
            *status* - ${{steps.check.outputs.status}}

      - name: Update datadog
        uses: masci/datadog@v1
        with:
          api-key: ${{ secrets.DATADOG_API_KEY }}
          api-url: "https://us5.datadoghq.com"
          metrics: |
            - type: "count"
              name: "promotions.count"
              value: 1.0
              host: ${{ github.repository_owner }}
              tags:
                - "branch:${{ github.head_ref }}"
                - "status:${{ steps.check.outputs.status }}"
                - "version:${{ needs.tag.outputs.semver }}"
