# workflow jobs for testing/linting and verifying changes to go packages
---
name: pkg
"on":
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: read
  packages: write
  pull-requests: write
  statuses: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:
  changes:
    name: üîç changes
    runs-on: ubuntu-latest
    outputs:
      pkg: ${{ steps.filter.outputs.pkg }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            pkg:
              - 'pkg/**'
              - .github/workflows/pkg.yml
              - go.mod
              - go.sum
  lint:
    name: üåè lint
    needs: changes
    if: ${{ needs.changes.outputs.pkg == 'true' }}
    defaults:
      run:
        working-directory: pkg
    runs-on: [ubuntu-latest-16-cores, linux]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup for CI
        uses: powertoolsdev/mono/actions/setup-ci@main

      - name: Lint
        run: |
          earthly \
            ${{ env.EARTHLY_EXTRA_ARGS }} \
            --remote-cache=ghcr.io/${{ github.repository }}-pkg:cache \
            +lint

  test:
    name: üåè test
    needs: changes
    if: ${{ needs.changes.outputs.pkg == 'true' }}
    defaults:
      run:
        working-directory: pkg
    runs-on: [ubuntu-latest-16-cores, linux]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup for CI
        uses: powertoolsdev/mono/actions/setup-ci@main

      - name: Test
        run: |
          earthly \
            ${{ env.EARTHLY_EXTRA_ARGS }} \
            --remote-cache=ghcr.io/${{ github.repository }}-pkg:cache \
            +test

  cache:
    name: üåè cache
    needs:
      - changes
      - test
    if: ${{ needs.changes.outputs.pkg == 'true' && github.event_name != 'pull_request' }}
    defaults:
      run:
        working-directory: pkg
    runs-on: [ubuntu-latest-16-cores, linux]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup for CI
        uses: powertoolsdev/action-setup-ci@main

      - name: cache
        run: |
          earthly \
            ${{ env.EARTHLY_EXTRA_ARGS }} \
            --push \
            --max-remote-cache \
            --remote-cache=ghcr.io/${{ github.repository }}-pkg:cache \
            +code

  release:
    name: Release
    needs:
      - changes
      - test
    if: ${{ needs.changes.outputs.protos == 'true' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine next version
        id: semver
        uses: ietf-tools/semver-action@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          patchAll: true
          prefix: pkg/
      - name: Push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.semver.outputs.nextStrict }}

  update_status:
    name: update status
    needs:
      - lint
      - test
      - release
    if: github.event_name == 'pull_request' && always()
    runs-on: ubuntu-latest
    steps:
      - uses: martialonline/workflow-status@v3
        id: check
      - name: Update status
        uses: ouzi-dev/commit-status-updater@v2.0.1
        with:
          name: pkg ‚úÖ
          status: ${{steps.check.outputs.status}}
