# workflows for interacting with protos and pushing our types to protos schema registry
---
name: pkg
"on":
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: read
  packages: write
  pull-requests: write
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      protos: ${{ steps.filter.outputs.pkg }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            protos:
              - 'pkg/**'
  lint:
    name: Lint pkg
    needs: changes
    if: ${{ needs.changes.outputs.pkg == 'true' }}
    defaults:
      run:
        working-directory: pkg
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup for CI
        uses: powertoolsdev/action-setup-ci@main
        with:
          tfcloud_token: ${{ secrets.TF_API_KEY }}

      - name: Lint
        run: |
          earthly \
            ${{ env.EARTHLY_EXTRA_ARGS }} \
            --remote-cache=ghcr.io/${{ github.repository }}:pkg-lint \
            +lint

  test:
    name: Test pkg
    needs: changes
    if: ${{ needs.changes.outputs.pkg == 'true' }}
    defaults:
      run:
        working-directory: pkg
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup for CI
        uses: powertoolsdev/action-setup-ci@main
        with:
          tfcloud_token: ${{ secrets.TF_API_KEY }}

      - name: Test
        run: |
          earthly \
            ${{ env.EARTHLY_EXTRA_ARGS }} \
            --remote-cache=ghcr.io/${{ github.repository }}:pkg-test \
            +test

  release:
    name: Release
    needs:
      - changes
      - test
    if: ${{ needs.changes.outputs.protos == 'true' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine next version
        id: semver
        uses: ietf-tools/semver-action@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          patchAll: true
          prefix: pkg/
      - name: Push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.semver.outputs.nextStrict }}

