---
name: prod
on: workflow_dispatch

permissions:
  contents: write
  id-token: write
  issues: read
  packages: write
  pull-requests: write
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  tag:
    name: Determine short ref
    runs-on: ubuntu-latest
    outputs:
      git_ref: ${{steps.git_ref.outputs.git_ref}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set git_ref output
        id: git_ref
        run: echo "git_ref=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  services:
    # since this runs as a matrix, name shows as `ðŸš¢ (workers-orgs)`
    name: ðŸš¢
    needs:
      - tag
    strategy:
      matrix:
        service:
          - api
          - orgs-api
          - workers-apps
          - workers-instances
          - workers-deployments
          - workers-executors
          - workers-installs
          - workers-instances
          - workers-orgs
    uses: ./.github/workflows/service.yml
    with:
      service: ${{matrix.service}}
      tag: ${{ needs.tag.outputs.git_ref }}
      prod: true
    secrets: inherit
