---
name: promote
on:
  workflow_dispatch:
    inputs:
      prod:
        type: boolean
        required: true
      stage:
        type: boolean
        required: true

permissions:
  contents: write
  id-token: write
  issues: read
  packages: write
  pull-requests: write
  statuses: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  tag:
    name: Determine short ref
    runs-on: ubuntu-latest
    outputs:
      git_ref: ${{steps.git_ref.outputs.git_ref}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set git_ref output
        id: git_ref
        run: echo "git_ref=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  start_slack_notifications:
    name: update promotions channel
    needs:
      - tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_ICON_EMOJI: ü§ñ
        SLACK_USERNAME: github-bot
        SLACK_WEBHOOK: ${{ secrets.PROMOTIONS_SLACK_WEBHOOK_URL }}
        SLACK_MESSAGE: |
          ‚õ¥  promoting `${{ needs.tag.outputs.git_ref }}`
          *stage* - ${{ inputs.stage }}
          *prod* - ${{ inputs.prod }}

  services:
    # since this runs as a matrix, name shows as `üö¢ (workers-orgs)`
    name: üö¢
    needs:
      - tag
    strategy:
      fail-fast: false
      matrix:
        service:
          - ctl-api
          - workers-apps
          - workers-canary
          - workers-executors
          - workers-installs
          - workers-orgs
    uses: ./.github/workflows/service.yml
    with:
      service: ${{matrix.service}}
      tag: ${{ needs.tag.outputs.git_ref }}
      prod: ${{ inputs.prod }}
      stage: ${{ inputs.stage }}
    secrets: inherit

  status_slack_notifications:
    name: update promotions channel
    if: always()
    needs:
      - tag
      - services
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: martialonline/workflow-status@v3
      id: check
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_ICON_EMOJI: ü§ñ
        SLACK_USERNAME: github-bot
        SLACK_WEBHOOK: ${{ secrets.PROMOTIONS_SLACK_WEBHOOK_URL }}
        SLACK_COLOR: ${{steps.check.outputs.status}}
        SLACK_MESSAGE: |
          ${{ steps.check.outputs.status == 'success' && 'üèÅüèÅ' || 'üö®üö®' }} finished promoting `${{ needs.tag.outputs.git_ref }}`
          *stage* - ${{ inputs.stage }}
          *prod* - ${{ inputs.prod }}
          *status* - ${{steps.check.outputs.status}}
