---
name: promote
on:
  push:
    branches:
      - promote

permissions:
  contents: write
  id-token: write
  issues: read
  packages: write
  pull-requests: write
  statuses: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  tag:
    name: Determine short ref
    runs-on: ubuntu-latest
    outputs:
      git_ref: ${{steps.git_ref.outputs.git_ref}}
      semver: ${{ steps.semver.outputs.nextStrict }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set git_ref output
        id: git_ref
        run: echo "git_ref=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Determine next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: promote
          minorList: ""
          patchAll: true

  start_slack_notifications:
    name: update promotions channel
    needs:
      - tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_ICON_EMOJI: ü§ñ
          SLACK_USERNAME: github-bot
          SLACK_WEBHOOK: ${{ secrets.PROMOTIONS_SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: |
            ‚õ¥  promoting `${{ needs.tag.outputs.git_ref }}`
            *stage* - true
            *prod* - true

  services:
    # since this runs as a matrix, name shows as `üö¢ (workers-orgs)`
    name: üö¢
    needs:
      - tag
    strategy:
      fail-fast: false
      matrix:
        service:
          - ctl-api
          - dashboard-ui
          - workers-infra-tests
          - workers-executors
          - wiki
    uses: ./.github/workflows/service.yml
    with:
      service: ${{matrix.service}}
      tag: ${{ needs.tag.outputs.semver }}
      prod: true
      stage: false
    secrets: inherit

  artifacts:
    # since this runs as a matrix, name shows as `üö¢ (workers-orgs)`
    name: üö¢
    needs:
      - tag
    strategy:
      fail-fast: false
      matrix:
        dir:
          - services/e2e
          - bins/cli
          - bins/runner
    uses: ./.github/workflows/artifact.yml
    with:
      dir: ${{matrix.dir}}
      tag: ${{ needs.tag.outputs.semver }}
      is_promotion: true
    secrets: inherit

  bump_tag:
    name: bump tag
    needs:
      - tag
    runs-on: ubuntu-latest
    steps:
      - name: Push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ needs.tag.outputs.semver }}

  update_statuses:
    name: update statuses
    needs:
      - tag
      - services
      - artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: martialonline/workflow-status@v4.1
        id: check
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_ICON_EMOJI: ü§ñ
          SLACK_USERNAME: github-bot
          SLACK_WEBHOOK: ${{ secrets.PROMOTIONS_SLACK_WEBHOOK_URL }}
          SLACK_COLOR: ${{steps.check.outputs.status}}
          SLACK_MESSAGE: |
            ${{ steps.check.outputs.status == 'success' && 'üèÅüèÅ' || 'üö®üö®' }} finished promoting `${{ needs.tag.outputs.git_ref }}`
            *prod* - true
            *status* - ${{steps.check.outputs.status}}

      - name: Update datadog
        uses: masci/datadog@v1
        with:
          api-key: ${{ secrets.DATADOG_API_KEY }}
          api-url: "https://us5.datadoghq.com"
          metrics: |
            - type: "count"
              name: "promotions.count"
              value: 1.0
              host: ${{ github.repository_owner }}
              tags:
                - "branch:${{ github.head_ref }}"
                - "status:${{ steps.check.outputs.status }}"
                - "version:${{ needs.tag.outputs.semver }}"

  promote_success:
    name: promote_success
    needs:
      - tag
      - bump_tag
      - artifacts
      - services
    uses: ./.github/workflows/promote_success.yml
    with:
      tag: ${{ needs.tag.outputs.semver }}
    secrets: inherit
