# workflows for interacting with protos and pushing our types to protos schema registry
---
name: protos
"on":
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: read
  packages: write
  pull-requests: write
  statuses: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  changes:
    name: üîç changes
    runs-on: ubuntu-latest
    outputs:
      protos: ${{ steps.filter.outputs.protos }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            protos:
              - 'pkg/types/**'
  lint:
    name: ‚úâÔ∏è  lint
    needs: changes
    if: ${{ needs.changes.outputs.protos == 'true' }}
    strategy:
      matrix:
        repo:
          - api
          - components
          - orgs-api
          - shared
          - workflows
    defaults:
      run:
        working-directory: pkg/types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup for CI
        uses: powertoolsdev/action-setup-ci@main
        with:
          tfcloud_token: ${{ secrets.TF_API_KEY }}
          buf_auth_token: ${{ secrets.BUF_AUTH_TOKEN }}

      - name: Lint
        run: |
          earthly \
            ${{ env.EARTHLY_EXTRA_ARGS }} \
            --ci \
            --remote-cache=ghcr.io/${{ github.repository }}:protos-lint \
            +lint \
            --REPO=${{matrix.repo}} \

  release:
    name: üöÄ release
    needs:
      - changes
      - lint
    if: ${{ needs.changes.outputs.protos == 'true' && github.event_name != 'pull_request' }}
    defaults:
      run:
        working-directory: pkg/types
    strategy:
      matrix:
        repo:
          - api
          - components
          - orgs-api
          - shared
          - workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup for CI
        uses: powertoolsdev/action-setup-ci@main
        with:
          tfcloud_token: ${{ secrets.TF_API_KEY }}
          buf_auth_token: ${{ secrets.BUF_AUTH_TOKEN }}

      - name: Push protos
        run: |
          earthly \
            ${{ env.EARTHLY_EXTRA_ARGS }} \
            +push-proto \
            --REPO=${{matrix.repo}} \

  update_status:
    name: update status
    if: github.event_name == 'pull_request' && always()
    runs-on: ubuntu-latest
    needs:
      - changes
      - lint
      - release
    steps:
      - uses: martialonline/workflow-status@v3
        id: check
      - name: Update status
        uses: ouzi-dev/commit-status-updater@v2.0.1
        with:
          name: protos ‚úÖ
          status: ${{steps.check.outputs.status}}
