# workflows for interacting with protos and pushing our types to protos schema registry
---
name: protos
"on":
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: read
  packages: write
  pull-requests: write
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      protos: ${{ steps.filter.outputs.protos }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            protos:
              - 'pkg/types/**'
  lint-protos:
    name: Lint protos
    needs: changes
    if: ${{ needs.changes.outputs.protos == 'true' }}
    strategy:
      matrix:
        repo:
          - api
          - components
          - orgs-api
          - shared
          - workflows
    defaults:
      run:
        working-directory: pkg/types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup for CI
        uses: powertoolsdev/action-setup-ci@main
        with:
          tfcloud_token: ${{ secrets.TF_API_KEY }}
          clone_token: ${{ steps.generate_token.outputs.token }}

      - name: Lint
        run: |
          earthly \
            ${{ env.EARTHLY_EXTRA_ARGS }} \
            --remote-cache=ghcr.io/mono:protos-lint \
            +lint \
            --REPO=${{matrix.repo}} \

  release-protos:
    name: Release protos
    needs: changes
    if: ${{ needs.changes.outputs.protos == 'true' && github.event_name != 'pull_request' }}
    defaults:
      run:
        working-directory: pkg/types
    strategy:
      matrix:
        repo:
          - api
          - components
          - orgs-api
          - shared
          - workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Push protos
        run: |
          earthly \
            ${{ env.EARTHLY_EXTRA_ARGS }} \
            --remote-cache=ghcr.io/${{ github.repository }}:protos \
            +push-proto \
            --REPO=${{matrix.repo}} \
  release:
    name: Release
    needs:
      - changes
      - release-protos
    if: ${{ needs.changes.outputs.protos == 'true' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine next version
        id: semver
        uses: ietf-tools/semver-action@v1.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          patchAll: true
          prefix: protos/
      - name: Push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.semver.outputs.nextStrict }}
