# workflows for interacting with protos and pushing our types to protos schema registry
---
name: protos
"on":
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: read
  packages: write
  pull-requests: write
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  changes:
    name: üîç changes
    runs-on: ubuntu-latest
    outputs:
      protos: ${{ steps.filter.outputs.protos }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            protos:
              - 'pkg/types/**'
  lint-protos:
    name: ‚úâÔ∏è  lint protos
    needs: changes
    if: ${{ needs.changes.outputs.protos == 'true' }}
    strategy:
      matrix:
        repo:
          - api
          - components
          - orgs-api
          - shared
          - workflows
    defaults:
      run:
        working-directory: pkg/types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup for CI
        uses: powertoolsdev/action-setup-ci@main
        with:
          tfcloud_token: ${{ secrets.TF_API_KEY }}
          buf_auth_token: ${{ secrets.BUF_AUTH_TOKEN }}

      - name: Lint
        run: |
          earthly \
            ${{ env.EARTHLY_EXTRA_ARGS }} \
            --remote-cache=ghcr.io/${{ github.repository }}:protos-lint-${{matrix.repo}} \
            +lint \
            --REPO=${{matrix.repo}} \

  release-protos:
    name: üöÄ release protos
    needs: changes
    if: ${{ needs.changes.outputs.protos == 'true' && github.event_name != 'pull_request' }}
    defaults:
      run:
        working-directory: pkg/types
    strategy:
      matrix:
        repo:
          - api
          - components
          - orgs-api
          - shared
          - workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup for CI
        uses: powertoolsdev/action-setup-ci@main
        with:
          tfcloud_token: ${{ secrets.TF_API_KEY }}
          buf_auth_token: ${{ secrets.BUF_AUTH_TOKEN }}

      - name: Push protos
        run: |
          earthly \
            ${{ env.EARTHLY_EXTRA_ARGS }} \
            --remote-cache=ghcr.io/${{ github.repository }}:protos \
            +push-proto \
            --REPO=${{matrix.repo}} \
