---
name: Release
"on":
  workflow_call:
    inputs:
      workspace:
        type: string
        required: false
      service:
        type: string
        required: false
      dir:
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  terraform:
    name: Get terraform outputs
    runs-on: ubuntu-latest
    env:
      TF_OUT: ${{ github.workspace }}/tf-out.json
      TF_WORKSPACE: ${{ inputs.workspace }}
    permissions:
      contents: read
    timeout-minutes: 7
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_KEY }}

      - name: Init terraform
        shell: bash
        working-directory: ${{ inputs.dir }}
        run: |
          terraform init

      - name: Get terraform outputs
        working-directory: ${{ inputs.dir }}
        run: |
          terraform-bin output -json > "${{ runner.temp }}/tf.out"

      - name: Parse terraform outputs
        uses: powertoolsdev/mono/actions/tf-output@main
        with:
          file: ${{ runner.temp }}/tf.out

      - name: Save terraform outputs
        run: |
          printenv | grep "TFO_" > "${{ runner.temp }}/.tfenv"

      - name: Save outputs
        uses: actions/upload-artifact@v3
        with:
          name: env-${{ github.run_id }}-${{inputs.service}}
          path: ${{ runner.temp }}/.tfenv
          if-no-files-found: error
          retention-days: 1
