# workflows for building/testing/deploying services
---
name: services
"on":
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: read
  packages: write
  pull-requests: write
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  # NOTE(jm): we only want to "cancel" in flight jobs if pushing to an existing PR. If this is running on main, do not
  # cancel previous jobs.
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:
  changes:
    name: ðŸ” changes
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api: services/api/**
            orgs-api: services/orgs-api/**
            workers-apps: services/workers-apps/**
            workers-deployments: services/workers-deployments/**
            workers-executors: services/workers-executors/**
            workers-instances: services/workers-instances/**
            workers-installs: services/workers-installs/**
            workers-orgs: services/workers-orgs/**

  tag:
    name: Determine short ref
    runs-on: ubuntu-latest
    outputs:
      git_ref: ${{steps.git_ref.outputs.git_ref}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set git_ref output
        id: git_ref
        run: echo "git_ref=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  services:
    # since this runs as a matrix, name shows as `ðŸš¢ (workers-orgs)`
    name: ðŸš¢
    needs:
      - changes
      - tag
    if: ${{ needs.changes.outputs.services != '[]' && needs.changes.outputs.services != '' }}
    strategy:
      matrix:
        service: ${{ fromJSON(needs.changes.outputs.services) }}
    uses: ./.github/workflows/service.yml
    with:
      service: ${{matrix.service}}
      tag: ${{ needs.tag.outputs.git_ref }}
    secrets: inherit
