# workflows for building/testing/deploying services
---
name: services
"on":
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: read
  packages: write
  pull-requests: write
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  # NOTE(jm): we only want to "cancel" in flight jobs if pushing to an existing PR. If this is running on main, do not
  # cancel previous jobs.
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            orgs-api: services/orgs-api/**
            workers-apps: services/workers-apps/**
            workers-deployments: services/workers-deployments/**
            workers-executors: services/workers-executors/**
            workers-instances: services/workers-instances/**
            workers-installs: services/workers-installs/**
            workers-orgs: services/workers-orgs/**

  tag:
    name: Determine next tag for services changed
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ github.event_name != 'pull_request' && steps.semver.outputs.next || 'local' }}
      tag_strict: ${{ github.event_name != 'pull_request' && steps.semver.outputs.nextStrict || 'local' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Determine next version
        if: github.event_name != 'pull_request'
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          patchAll: true

  services:
    name: Service job
    needs:
      - changes
      - tag
    if: ${{ needs.changes.outputs.services != '[]' && needs.changes.outputs.services != '' }}
    strategy:
      matrix:
        service: ${{ fromJSON(needs.changes.outputs.services) }}
    uses: ./.github/workflows/service.yml
    with:
      service: ${{matrix.service}}
      tag: ${{ needs.tag.outputs.tag }}
    secrets: inherit

  push_tag:
    name: Push tag to repo
    if: github.event_name != 'pull_request'
    needs:
      - tag
      - services
    runs-on: ubuntu-latest
    steps:
      - name: Push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ needs.tag.outputs.tag_strict }}
