---
name: Release
"on":
  workflow_call:
    inputs:
      service:
        type: string
        required: true
      tag:
        type: string
        required: true
    outputs:
      image_tag:
        description: "image tag"
        value: ${{ jobs.release.outputs.image_tag }}

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Release
    runs-on: [ubuntu-latest-16-cores, linux]
    permissions:
      contents: read
      packages: write
      id-token: write
    outputs:
      image_tag: ${{ inputs.tag }}
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download terraform outputs
        uses: actions/download-artifact@v4
        with:
          name: env-${{ github.run_id }}-${{inputs.service}}-env

      - name: Setup environment
        run: |
          cat .tfenv >> "$GITHUB_ENV"

      - name: Setup for CI
        uses: powertoolsdev/mono/actions/setup-ci@main
        with:
          tfcloud_token: ${{ secrets.TF_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          aws_role: ${{ env.TFO_GH_ROLE_ARN }}
          aws_region: ${{ env.TFO_REGION }}
          ecr_registries: ${{ env.TFO_ECR_REGISTRY_ID }}
          setup_helm: "false"

      - name: Build and push container
        working-directory: services/${{inputs.service}}
        run: |
          earthly \
            ${{ env.EARTHLY_EXTRA_ARGS }} \
            --ci \
            --push \
            --remote-cache=ghcr.io/${{ github.repository }}-pkg:cache \
            +docker \
            --repo=${{ env.TFO_ECR_REPOSITORY_URL }} \
            --image_tag=${{ inputs.tag }}

      - name: Bump and publish chart
        working-directory: services/${{inputs.service}}/k8s
        run: |
          earthly \
            ${{ env.EARTHLY_EXTRA_ARGS }} \
            --remote-cache=ghcr.io/${{ github.repository }}-helm:cache \
            --push \
            --max-remote-cache \
            +helm-bump-and-publish \
            --chart_name=${{ inputs.service }} \
            --chart_version=v0.0.1-${{ inputs.tag }}

      - name: Handle failures
        if: failure()
        run: |
          earthly \
            ${{ env.EARTHLY_EXTRA_ARGS }} \
            github.com/powertoolsdev/shared-configs+helm-unrelease \
            --repo_name=${{ github.repository }} \
            --registry_id=${{ env.TFO_ECR_REGISTRY_ID }} \
            --chart_version=v0.0.1-${{ inputs.tag }} \
            --image_tag=${{ inputs.tag }} \
            --helm_repos="nuon=${{ env.TFO_NUON_CHARTS }}" \
          || true
