---
name: skip-ci
"on":
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: read
  packages: write
  pull-requests: write
  statuses: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  # NOTE(jm): we only want to "cancel" in flight jobs if pushing to an existing PR. If this is running on main, do not
  # cancel previous jobs.
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:
  checks:
    name: üîç checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check: [
         services ‚úÖ,
         artifacts ‚úÖ,
         pkg ‚úÖ,
         infra ‚úÖ,
         protos ‚úÖ,
         pull_request ‚úÖ,
         branch ‚úÖ,
         lint ‚úÖ,
         Terraform Cloud/nuonco/infra-artifacts,
         Terraform Cloud/nuonco/aws-accounts,
         Terraform Cloud/nuonco/aws-org,
         Terraform Cloud/nuonco/aws-sso,
         Terraform Cloud/nuonco/infra-datadog-orgs-prod,
         Terraform Cloud/nuonco/infra-datadog-orgs-stage,
         Terraform Cloud/nuonco/infra-datadog-prod,
         Terraform Cloud/nuonco/infra-datadog-stage,
         Terraform Cloud/nuonco/infra-eks-orgs-prod-main,
         Terraform Cloud/nuonco/infra-eks-orgs-stage-main,
         Terraform Cloud/nuonco/infra-eks-prod-nuon,
         Terraform Cloud/nuonco/infra-eks-stage-nuon,
         Terraform Cloud/nuonco/infra-github,
         Terraform Cloud/nuonco/infra-orgs-prod,
         Terraform Cloud/nuonco/infra-orgs-stage,
         Terraform Cloud/nuonco/infra-temporal-prod,
         Terraform Cloud/nuonco/infra-temporal-stage,
         Terraform Cloud/nuonco/infra-terraform,
         Terraform Cloud/nuonco/infra-waypoint-orgs-prod,
         Terraform Cloud/nuonco/infra-waypoint-orgs-stage,
         Terraform Cloud/nuonco/nuon-dns,
         Terraform Cloud/nuonco/powertools,
         Terraform Cloud/nuonco/e2e-prod,
         Terraform Cloud/nuonco/e2e-stage,
         Terraform Cloud/nuonco/ctl-api-prod,
         Terraform Cloud/nuonco/ctl-api-stage,
         Terraform Cloud/nuonco/dashboard-ui-prod,
         Terraform Cloud/nuonco/dashboard-ui-stage,
         Terraform Cloud/nuonco/workers-apps-prod,
         Terraform Cloud/nuonco/workers-apps-stage,
         Terraform Cloud/nuonco/workers-canary-prod,
         Terraform Cloud/nuonco/workers-canary-stage,
         Terraform Cloud/nuonco/workers-executors-prod,
         Terraform Cloud/nuonco/workers-executors-stage,
         Terraform Cloud/nuonco/workers-installs-prod,
         Terraform Cloud/nuonco/workers-installs-stage,
         Terraform Cloud/nuonco/workers-orgs-prod,
         Terraform Cloud/nuonco/workers-orgs-stage]
    steps:
      - name: update statuses
        if: contains( github.event.pull_request.labels.*.name, 'skip-ci')
        uses: ouzi-dev/commit-status-updater@v2.0.1
        with:
          name: ${{ matrix.check }}
          status: success
