---
name: skip-ci
"on":
  pull_request:
  merge_group:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: read
  packages: write
  pull-requests: write
  statuses: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  # NOTE(jm): we only want to "cancel" in flight jobs if pushing to an existing PR. If this is running on main, do not
  # cancel previous jobs.
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:
  checks:
    name: ğŸ” checks
    runs-on: ubuntu-latest
    # NOTE(jm): by doing this all inline, we only have a single result on the final PR, which makes it easier to read
    # than parsing the output of matrix
    steps:
      - name: set services
        if: contains( github.event.pull_request.labels.*.name, 'skip-ci')
        uses: ouzi-dev/commit-status-updater@v2.0.1
        with:
          name: services âœ…
          status: success
      - name: set artifacts
        if: contains( github.event.pull_request.labels.*.name, 'skip-ci')
        uses: ouzi-dev/commit-status-updater@v2.0.1
        with:
          name: artifacts âœ…
          status: success
      - name: set pkg
        if: contains( github.event.pull_request.labels.*.name, 'skip-ci')
        uses: ouzi-dev/commit-status-updater@v2.0.1
        with:
          name: pkg âœ…
          status: success
      - name: set protos
        if: contains( github.event.pull_request.labels.*.name, 'skip-ci')
        uses: ouzi-dev/commit-status-updater@v2.0.1
        with:
          name: protos âœ…
          status: success
      - name: set pull_request
        if: contains( github.event.pull_request.labels.*.name, 'skip-ci')
        uses: ouzi-dev/commit-status-updater@v2.0.1
        with:
          name: pull_request âœ…
          status: success
      - name: set branch
        if: contains( github.event.pull_request.labels.*.name, 'skip-ci')
        uses: ouzi-dev/commit-status-updater@v2.0.1
        with:
          name: branch âœ…
          status: success
      - name: set lint
        if: contains( github.event.pull_request.labels.*.name, 'skip-ci')
        uses: ouzi-dev/commit-status-updater@v2.0.1
        with:
          name: lint âœ…
          status: success
      - name: set terraform cloud
        if: contains( github.event.pull_request.labels.*.name, 'skip-ci')
        uses: ouzi-dev/commit-status-updater@v2.0.1
        with:
          name: Terraform Cloud/nuonco/repo-id-B14tP6vG7ia3CQHo
          status: success
