---
name: terraform-outputs
"on":
  workflow_call:
    inputs:
      workspace:
        type: string
        required: false
      cache-key:
        type: string
        required: false
      dir:
        type: string
        required: true
      static_workspace:
        type: boolean
        required: false
        default: false
    outputs:
      outputs_cache_key:
        description: "plain outputs"
        value: ${{ jobs.terraform.outputs.outputs_cache_key }}
      env_cache_key:
        description: "env cache key"
        value: ${{ jobs.terraform.outputs.env_cache_key }}
      tf_env:
        description: "tf env path, where terraform outputs are written in environment variable form (ie: TFO_ prefix)"
        value: ${{ jobs.terraform.outputs.tf_env }}
      tf_out:
        description: "tf out path, where terraform outputs are written"
        value: ${{ jobs.terraform.outputs.tf_out }}

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  terraform:
    name: Get terraform outputs
    runs-on: ubuntu-latest
    env:
      TF_OUT: ${{ github.workspace }}/tf-out.json
      TF_ENV: ${{ github.workspace }}/.tfenv
    outputs:
      tf_out: ${{ steps.save_output_vars.outputs.tf_out }}
      tf_env: ${{ steps.save_output_vars.outputs.tf_env }}
      env_cache_key: ${{ steps.save_output_vars.outputs.env_cache_key }}
      outputs_cache_key: ${{ steps.save_output_vars.outputs.outputs_cache_key }}
    permissions:
      contents: read
    timeout-minutes: 7
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_KEY }}

      - name: Set TF workspace
        if: ${{ !inputs.static_workspace }}
        run: echo TF_WORKSPACE=${{ inputs.workspace }} > $GITHUB_ENV

      - name: Init terraform
        working-directory: ${{ inputs.dir }}
        run: |
          terraform init

      - name: Get terraform outputs
        working-directory: ${{ inputs.dir }}
        run: |
          terraform-bin output -json > "${{ env.TF_OUT }}"

      - name: Parse terraform outputs
        uses: powertoolsdev/mono/actions/tf-output@main
        with:
          file: ${{ env.TF_OUT }}
          cleanup: false

      - name: Save terraform outputs
        run: |
          printenv | grep "TFO_" > "${{ env.TF_ENV }}"

      - name: Save output vars
        id: save_output_vars
        run: |
          echo tf_out=${{ env.TF_OUT }} >> "$GITHUB_OUTPUT"
          echo tf_env=${{ env.TF_ENV }} >> "$GITHUB_OUTPUT"
          echo env_cache_key=env-${{ github.run_id }}-${{ inputs.cache-key }}-env >> "$GITHUB_OUTPUT"
          echo outputs_cache_key=env-${{ github.run_id }}-${{ inputs.cache-key }}-outputs >> "$GITHUB_OUTPUT"

      - name: Save env outputs
        uses: actions/upload-artifact@v3
        with:
          name: env-${{ github.run_id }}-${{inputs.cache-key}}-env
          path: ${{ env.TF_ENV }}
          if-no-files-found: error
          retention-days: 1

      - name: Save tf outputs
        uses: actions/upload-artifact@v3
        with:
          name: env-${{ github.run_id }}-${{inputs.cache-key}}-outputs
          path: ${{ env.TF_OUT }}
          if-no-files-found: error
          retention-days: 1
