# Workflow to test experimental github action
name: Nuon Github Action Test

on:
  push:
    branches:
      - ja/3496-github-action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ja/3496-github-action
      - name: Deploy with Nuon
        uses: powertoolsdev/mono/exp/github-action@ja/3496-github-action
        with:
          # sandbox org
          org_id: orgvwpbd584d7v7o9x8oxqfo6b
          # I saved my own API token as a repo secret
          api_token: ${{ secrets.JORDAN_TEST_NUON_API_TOKEN }}
          # electric sql helm chart
          component_id: cmp7g1y7wsg1mjz8k878b2cucg
