---
type: worker
env:
  DISABLE_METRICS: true
  API_URL: http://localhost:8081
  INTERNAL_API_URL: http://localhost:8082
  TERRAFORM_MODULE_DIR: ./terraform
  TESTS_DIR: ./tests
  INSTALL_SCRIPT_PATH: ./install-cli.sh
  DISABLE_NOTIFICATIONS: true
  DISABLE_TESTS: false
  CANARY_DEBUG_PERIOD: 30s

local_startup_cmds:
  - go build -o /tmp/svc-workers-canary .
local_cmds:
  - /tmp/svc-workers-canary all
earthly_cmd: all
