---
type: worker
env:
  DISABLE_METRICS: true
  API_URL: http://localhost:8081
  GITHUB_INSTALL_ID: "41323514"
  TERRAFORM_MODULE_DIR: ../e2e/nuon
  INSTALL_SCRIPT_PATH: ./install-cli.sh
local_startup_cmds:
  - go build -o /tmp/svc-workers-canary .
local_cmds:
  - /tmp/svc-workers-canary all
earthly_cmd: all
